### ISSUE TITLE
baseline pupil measurements in dark/light

### ISSUE THREAD

**Issue by anne-urai** [anne-urai/human_ibl_snapshots#41]

**Comment by anne-urai** [comment]
after pupil calibration, before task starts?

https://elifesciences.org/articles/87022 figure 1d

**Comment by phijoh** [comment]
reply from Stijn:

The white and black screen really were as simple as that. One quick note though, we initially thought that those screens would result in (approximations of) the upper and lower limits of pupil size for each participant and that we could express all the following pupil measurements as a % of that range. That was, however, not the case and for almost all participants their pupil size dropped below what we measured during the bright screen (and same for the upper limit during black screen).

**Comment by phijoh** [comment]
yes, sounds like it doesn't give us a useful estimate of max and min pupil size, so I think no point including them. Unless we want a very basic check of data quality. I don't think it's necessary though
