### ISSUE TITLE
final wrap-up meeting

### ISSUE THREAD

**Issue by anne-urai** [anne-urai/human_ibl_snapshots#52]

**Comment by anne-urai** [comment]
To discuss and do
- [ ] ECVP poster in the hallway
- [ ]

**Comment by anne-urai** [comment]
### wrap-up meeting
- all documentation lives on [gdrive](https://drive.google.com/drive/u/0/folders/1DDTWxcqAGG8JOesavHk1mzbKXyA4MbXb)
- code updated and forked to [cocosys](https://github.com/cocosys-lab/human_IBL_cursor)

**Comment by anne-urai** [comment]
### lab clean-up, 19 Dec
- [ ] consent forms and USB sticks should go into locked cabinet in Anne's office
- [ ] tripod and mirror into SOLO storage (or Anne's office?)
- [ ] webcam back to SOLO, or can we keep it for now (at least keep track of which exact one it was)?
- [x] all participants paid

**Comment by anne-urai** [comment]
### webcam
It's a Logitech b525, spoke to lab support and they said they would leave it in 2.508 so we know where to find it
 ![Image](https://github.com/user-attachments/assets/5514cfa2-4789-4471-8d65-14325a6b89b0)
![Image](https://github.com/user-attachments/assets/570050df-10c4-4356-bdc2-d8bc925316a8)

**Comment by LorenzovHoorde** [comment]
The info on the box of the camera is a bit more concrete
![IMG20241219155008](https://github.com/user-attachments/assets/018c13f6-8147-492c-9f94-770e9a72d8e4)

**Comment by LorenzovHoorde** [comment]
> * [x]  consent forms and USB sticks should go into locked cabinet in Anne's office
> * [x]  tripod and mirror into SOLO storage (or Anne's office?)
> * [x]  webcam back to SOLO, or can we keep it for now (at least keep track of which exact one it was)?
> * [x]  all participants paid

All done!
