### ISSUE TITLE
Instructions / breaks

### ISSUE THREAD

**Issue by cami-uche-enwe** [anne-urai/human_ibl_snapshots#8]
Investigate instruction-experience gap (RL vs instructional learning in the IBL task)

**Comment by cami-uche-enwe** [comment]
Could have two versions:
- full instructions (as is now)
- little to no instructions: mimic how mice have to learn the task purely through experience

_For implementing in Pavlovia: could we have one experiment with two versions coded into it (eg. as conditions) or would we need two separate experiments?_

**Comment by anne-urai** [comment]
related paper: https://www-nature-com.ezproxy.leidenuniv.nl/articles/s41593-024-01607-5

**Comment by cami-uche-enwe** [comment]
"You will see a fixation cross in the middle of the screen; please keep you eyes focused on this fixation cross throughout the experiment.
 
At the beginning of each trial you will hear a sharp beep. 
You will then see two targets appear on each side of the screen. 
You must choose the target with the stronger contrast: to do this, simply drag the mouse to move the chosen target to the center of the screen. 
For example, if the right target has the stronger contrast, move your mouse to the left. 
If the left target has the stronger contrast, move your mouse to the right.
Simply moving the mouse is enough, you don't need to click anything.

You will hear a high beep if you answered correctly. If you answer incorrectly, you will hear a buzzing noise instead. If you take too long to answer, you will hear a low beep.

Please try to be as fast and accurate as possible.

Click 'Continue' to see some examples."

**Comment by anne-urai** [comment]
- [ ] insert consent form + debrief text
- [ ] two versions of the instructions
- [ ] think about a scheme for counterbalancing so that there are 4 groups (2x2, instructions and breaks)

**Comment by anne-urai** [comment]
Decision: first estimate how many participants we can get (ideally, 6 weeks x 5 days x 6 people/day)

**Comment by cami-uche-enwe** [comment]
short and long instructions implemented (no breaks manipulation anymore)
pID determines instructions received following a YYNN sequence (so it doesn't overlap with parity of stimulus sequences)
